# version: "3.9"

services:
  db:
    image: postgres:16-alpine3.19
    restart: always
    env_file:
      - .env
    # ports:
    #   - "${DATABASE_PORT:5432}"
    networks:
      - app-network
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5




  api:
    build: .
    env_file:
      - .env
    environment:
      - MODE=production
    ports:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/usr/src/app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: