# Generated by Django 5.1.4 on 2024-12-11 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='csvs/%Y/%m/%d/')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/%d/')),
                ('hash', models.CharField(max_length=1000, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='extract.pdf'),
        ),
    ]
